name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, alpha]

jobs:
  smoke-test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: ["20", "22"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --lockfile-only
      - name: Print Node.js and pnpm versions
        run: |
          node -v
          pnpm -v
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
